/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MultiEscrow } from "./MultiEscrow";

export { MultiEscrow__factory } from "./factories/MultiEscrow__factory";
